services:
  - type: web
    name: codehub
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: APP_ADMIN_EMAIL
        value: chetanjha888@gmail.com
      - key: JWT_SECRET
        generateValue: true
      - key: MAX_FAILED_LOGIN_ATTEMPTS
        value: 5
      - key: ACCOUNT_LOCKOUT_MINUTES
        value: 15
      - key: RATE_LIMIT_WINDOW_SECONDS
        value: 60
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 20
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
