server.port=${PORT:8080}
spring.application.name=codehub-gateway
management.endpoints.web.exposure.include=health,info
codehub.auth-service-url=${AUTH_SERVICE_URL:http://localhost:8081}
codehub.snippet-service-url=${SNIPPET_SERVICE_URL:http://localhost:8082}
codehub.notification-admin-service-url=${NOTIFICATION_ADMIN_SERVICE_URL:http://localhost:8083}
